### PR TITLE
Feature/ssrs 2016

### PR DESCRIPTION
**Pull request by chaim1221**
the work I did in November on the reports

### CODE REVIEW

**Comment by jcii** [comment]
:white_check_mark: [Build Machete 1.0.197 completed](https://ci.appveyor.com/project/jcii/machete/build/1.0.197) (commit https://github.com/SavageLearning/Machete/commit/edfed3eb59 by @chaim1221)

**Comment by jcii** [comment]
well arent you fancy getting #200

**Comment by jcii** [comment]
:white_check_mark: [Build Machete 1.0.248 completed](https://ci.appveyor.com/project/jcii/machete/build/1.0.248) (commit https://github.com/SavageLearning/Machete/commit/2d3c7d5e40 by @chaim1221)

**Comment by jcii** [comment]
:white_check_mark: [Build Machete 1.0.257 completed](https://ci.appveyor.com/project/jcii/machete/build/1.0.257) (commit https://github.com/SavageLearning/Machete/commit/4d8886e901 by @chaim1221)

**Comment by chaim1221** [comment]
too stale to merge

**Pull request closed without merging**
